title: 6 toits

options:
  preview: https://azertypow.github.io/les6toits.front/

columns:
  sitepage:
    width: 1/1
    sections:
      published:
        headline: Publié
        type: pages
        status: listed
        layout: cards
        size: large
        sortBy: false
        image:
          cover: true

